//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CryptoCoin
    {
        public int Id { get; set; }
        public string CoinName { get; set; }
        public string PictureURI { get; set; }
        public double UnitPrice { get; set; }
        public double MarketCap { get; set; }
        public string Change24h { get; set; }
    }
}
